# Generated by Django 4.2.23 on 2025-07-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='pending_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
