# Generated by Django 4.2.23 on 2025-07-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_establishment_pending_deletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='website',
        ),
        migrations.AlterField(
            model_name='establishment',
            name='pork_type',
            field=models.CharField(choices=[('TRAD', 'Traditionnel'), ('FOUR', 'Au four'), ('AIL', "A l'ail"), ('AUTRE', 'Autre recette')], max_length=10),
        ),
    ]
